from __future__ import annotations

from typing import Any, Protocol


class StorageAdapter(Protocol):
    def ensure_schema(self) -> None: ...

    def get_truth(self, owner: str = ...) -> dict[str, Any]: ...

    def save_truth(self, truth: dict[str, Any], owner: str = ...) -> dict[str, Any]: ...

    def list_applications(self, owner: str = ...) -> list[dict[str, Any]]: ...

    def get_application(self, application_id: str, owner: str = ...) -> dict[str, Any] | None: ...

    def upsert_application(
        self, meta: dict[str, Any], *, jd_text: str | None = None, owner: str = ...
    ) -> dict[str, Any]: ...

    def delete_application(self, application_id: str, owner: str = ...) -> None: ...

    def get_jd(self, application_id: str, owner: str = ...) -> str: ...

    def list_generations(self, application_id: str, owner: str = ...) -> list[dict[str, Any]]: ...

    def get_generation(
        self, application_id: str, generation_id: str, owner: str = ...
    ) -> dict[str, Any] | None: ...

    def save_generation(
        self,
        application_id: str,
        *,
        generation: dict[str, Any],
        content: str,
        owner: str = ...,
    ) -> dict[str, Any]: ...

    def approve_generation(
        self, application_id: str, generation_id: str, owner: str = ...
    ) -> dict[str, Any]: ...

    def delete_generation(
        self, application_id: str, generation_id: str, owner: str = ...
    ) -> None: ...
